[package]
name = "warehouse_receipts"
version = "0.0.1"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "32300a2ab6dc95c25ff42e30b89990492ad4dcaa" }
multicoin = { git = "https://github.com/Algorithmic-Warfare/multicoin", subdir = "packages/multicoin", rev = "e384bbc8670b850cfb82a5e3b9fa46798b0ff6dc" }

[environments]
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
testnet_wip = "4c78adac"

[dep-replacements.testnet_wip]
multicoin = { use-environment = "testnet_stillness" }
world  = { use-environment = "testnet_stillness" }