[package]
name = "warehouse_receipts"
version = "0.0.1"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "8e2e97b50fd6bbf605284bcdaae54a33a5475e89" }
multicoin = { git = "https://github.com/Algorithmic-Warfare/multicoin.git", subdir = "packages/multicoin", rev = "281bd7dab874d34acfba107a6a010c1cd03ae43a" }

[environments]
testnet_utopia = "0xcaefce5e087e4ace962a2964f8df4df3fc33600171d5402574ea5ec38f9f46ce"
testnet_stillness = "0x0"
