[package]
name = "tribal_vault"
version = "0.0.1"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "8e2e97b50fd6bbf605284bcdaae54a33a5475e89" }
multicoin = { git = "https://github.com/Algorithmic-Warfare/multicoin.git", subdir = "packages/multicoin", rev = "9319d7d3a511f8c2e8e761289ce6810b014533ed" }

[environments]
testnet = "0x0"
testnet_utopia = "0x0"
testnet_stillness = "0x0"
