name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
      - name: Install Sui using Homebrew
        run: /home/linuxbrew/.linuxbrew/bin/brew install sui
      - name: setup sui config for localnet
        run: |
          sui client active-env || sui client switch --env localnet
      - name: Show Sui version
        run: sui --version || true
      - name: Build
        run: cd packages/contracts && sui move build
      - name: Test
        run: cd packages/contracts && sui move test
  
  move-formatter:
    name: Check Move files formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: npm i @mysten/prettier-plugin-move
      - run: npx prettier-move -c packages/contracts/**/*.move

  # deploy-testnet:
  #   if: github.ref == 'refs/heads/main'
  #   needs: 
  #     - build-test
  #     - move-formatter
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install Homebrew
  #       run: |
  #         /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  #         echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
  #     - name: Install Sui using Homebrew
  #       run: /home/linuxbrew/.linuxbrew/bin/brew install sui
  #     - name: setup sui config for testnet
  #       run: |
  #         sui client active-env || sui client switch --env testnet
  #     - name: Dry-run publish
  #       run: sui client publish --skip-fetch-latest-gas-price --gas-budget 30000000 --dry-run .
